### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by TheMinisterOfSound** [kiooeht/ModTheSpire#107]
I have everything up to date but when I try to start MTS it crashes these are the logs:

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (10-11-2018)
 - ModTheSpire (3.3.0)
Mod list:
 - basemod (4.0.2)
 - BlackRuseMod (0.9.2.2)
 - TS05_Marisa (0.13.6)
 - witchmod (1.1.2)
 - ReplayTheSpireMod (1.1.15)

Begin patching...
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
libgdx version 1.9.5
21:58:25.082 INFO basemod.BaseMod> initializeGson
21:58:25.085 INFO basemod.BaseMod> initializeTypeMaps
21:58:25.088 INFO basemod.BaseMod> Registered MonsterStrings
21:58:25.092 INFO basemod.BaseMod> Registered PowerStrings
21:58:25.094 INFO basemod.BaseMod> Registered CardStrings
21:58:25.098 INFO basemod.BaseMod> Registered RelicStrings
21:58:25.103 INFO basemod.BaseMod> Registered EventStrings
21:58:25.107 INFO basemod.BaseMod> Registered PotionStrings
21:58:25.111 INFO basemod.BaseMod> Registered CreditStrings
21:58:25.114 INFO basemod.BaseMod> Registered TutorialStrings
21:58:25.115 INFO basemod.BaseMod> Registered KeywordStrings
21:58:25.120 INFO basemod.BaseMod> Registered ScoreBonusStrings
21:58:25.124 INFO basemod.BaseMod> Registered CharacterStrings
21:58:25.126 INFO basemod.BaseMod> Registered UIStrings
21:58:25.136 INFO basemod.BaseMod> Registered OrbStrings
21:58:25.137 INFO basemod.BaseMod> Registered RunModStrings
21:58:25.141 INFO basemod.BaseMod> Registered BlightStrings
21:58:25.145 INFO basemod.BaseMod> Registered AchievementStrings
21:58:25.146 INFO basemod.BaseMod> initializePowerMap
21:58:25.991 INFO basemod.BaseMod> initializeUnderscorePowerIDs
21:58:26.037 INFO blackrusemod.BlackRuseMod> ========================= BLACKRUSEMOD INIT =========================
21:58:26.039 INFO blackrusemod.BlackRuseMod> subscribing to everything
21:58:26.040 INFO blackrusemod.BlackRuseMod> creating the color SILVER
21:58:26.040 INFO blackrusemod.BlackRuseMod> ================================================================
21:58:26.069 INFO ThMod_FnH.ThMod> creating the color : MARISA_COLOR
21:58:26.094 INFO witchmod.WitchMod> Initializing Witch Mod
21:58:26.136 INFO replayTheSpire.ReplayTheSpireMod> ========================= ReplayTheSpireMod INIT =========================
21:58:26.143 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: madsciencemod.MadScienceMod
21:58:26.144 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: fruitymod.FruityMod
21:58:26.145 INFO replayTheSpire.ReplayTheSpireMod> Found mod: blackrusemod.BlackRuseMod
21:58:26.146 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: fetch.FetchMod
21:58:26.148 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: infinitespire.InfiniteSpire
21:58:26.151 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: coloredmap.ColoredMap
21:58:26.153 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: com.evacipated.cardcrawl.mod.hubris.HubrisMod
21:58:26.154 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: com.evacipated.cardcrawl.mod.stslib.StSLib
21:58:26.156 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: mysticmod.MysticMod
21:58:26.158 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: beaked.Beaked
21:58:26.159 INFO replayTheSpire.ReplayTheSpireMod> Could not find mod: chronomuncher.ChronoMod
21:58:26.159 INFO replayTheSpire.ReplayTheSpireMod> ================================================================
Done.

Starting game...
21:58:26.169 INFO desktop.DesktopLauncher> time: 1539899906169
21:58:26.174 INFO desktop.DesktopLauncher> version: 2018-10-11
21:58:26.175 INFO desktop.DesktopLauncher> libgdx:  1.9.5
21:58:26.180 INFO desktop.DesktopLauncher> default_locale: en_US
21:58:26.181 INFO desktop.DesktopLauncher> default_charset: windows-1251
21:58:26.183 INFO desktop.DesktopLauncher> default_encoding: Cp1251
21:58:26.184 INFO desktop.DesktopLauncher> java_version: 1.8.0_144
21:58:26.184 INFO desktop.DesktopLauncher> os_arch: amd64
21:58:26.185 INFO desktop.DesktopLauncher> os_name: Windows 10
21:58:26.186 INFO desktop.DesktopLauncher> os_version: 10.0
21:58:26.187 INFO core.SystemStats> MEMORY STATS:
Free Memory: 97Mb
Max Memory: 1 804Mb
Allocated Memory: 509Mb
Unallocated Memory: 1 295Mb
Total Free Memory: 1 392Mb
Used Memory: 412Mb

21:58:26.194 INFO core.SystemStats> DISK STATS:
Total Space: 858 481Mb
Usable Space: 461 942Mb
Free Space: 461 942Mb

[Thread-6] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[Thread-6] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames21:58:26.364 INFO core.DisplayConfig> Reading info.displayconfig
21:58:26.371 INFO core.DisplayConfig> DisplayConfig successfully read.
21:58:26.374 INFO desktop.DesktopLauncher> Settings successfully loaded
21:58:26.375 INFO desktop.DesktopLauncher> Launching application...
21:58:27.269 INFO ststwitch.TwitchConfig> The 'twitchconfig.txt' already exists, not overwriting it.
21:58:27.434 INFO steam.SteamIntegration> [FAILURE] Steam API failed to initialize correctly.
No migration
21:58:27.444 INFO core.DisplayConfig> Reading info.displayconfig
21:58:27.449 INFO core.DisplayConfig> DisplayConfig successfully read.
21:58:27.460 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=preferences\1_STSSound
21:58:27.468 INFO helpers.AsyncSaver> Enqueue: qsize=1 file=preferences\1_STSGameplaySettings
21:58:27.472 INFO helpers.AsyncSaver> Enqueue: qsize=2 file=preferences\1_STSGameplaySettings
21:58:27.486 INFO helpers.FileSaver> Dequeue: qsize=2 file=preferences\1_STSSound
21:58:27.526 INFO helpers.File> Attempting to save file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSSound
21:58:27.570 INFO helpers.File> Successfully saved file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSSound
21:58:27.571 INFO helpers.FileSaver> Dequeue: qsize=1 file=preferences\1_STSGameplaySettings
21:58:27.572 INFO helpers.File> Attempting to save file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSGameplaySettings
21:58:27.575 INFO localization.LocalizedStrings> Loc Strings load time: 83ms
21:58:27.577 INFO basemod.BaseMod> begin editing localization strings
21:58:27.581 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RunModStrings
21:58:27.583 INFO blackrusemod.BlackRuseMod> begin editting strings
21:58:27.585 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
21:58:27.588 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
21:58:27.596 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
21:58:27.597 INFO blackrusemod.BlackRuseMod> done editting strings
21:58:27.597 INFO ThMod_FnH.ThMod> start editing strings
21:58:27.598 INFO ThMod_FnH.ThMod> lang == eng
21:58:27.600 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
21:58:27.606 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
21:58:27.609 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
21:58:27.610 INFO ThMod_FnH.ThMod> done editing strings
21:58:27.612 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
21:58:27.615 INFO replayTheSpire.ReplayTheSpireMod> begin editting strings
21:58:27.617 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
21:58:27.626 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
21:58:27.629 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
21:58:27.632 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.EventStrings
21:58:27.635 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.EventStrings
21:58:27.638 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PotionStrings
21:58:27.640 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.UIStrings
21:58:27.641 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.MonsterStrings
21:58:27.643 INFO replayTheSpire.ReplayTheSpireMod> Replay | Fetch not detected
21:58:27.648 INFO replayTheSpire.ReplayTheSpireMod> Replay | Fetch not detected
21:58:27.651 INFO replayTheSpire.ReplayTheSpireMod> Replay | Colored Map not detected
21:58:27.651 INFO replayTheSpire.ReplayTheSpireMod> done editting strings
21:58:27.664 INFO helpers.File> Successfully saved file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSGameplaySettings
21:58:27.665 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\1_STSGameplaySettings
21:58:27.667 INFO helpers.File> Attempting to save file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSGameplaySettings
21:58:27.723 INFO helpers.File> Successfully saved file=D:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\1_STSGameplaySettings
21:58:27.747 INFO audio.MusicMaster> Music Volume: 0.5
21:58:27.752 INFO audio.SoundMaster> Sound Effect Volume: 0.5
21:58:27.753 INFO audio.SoundMaster> Loaded 358 Sound Effects
21:58:27.753 INFO audio.SoundMaster> SFX load time: 3ms
21:58:29.212 INFO cards.AbstractCard> Card Image load time: 1444ms
21:58:29.216 INFO basemod.BaseMod> editting keywords
21:58:29.218 INFO blackrusemod.BlackRuseMod> setting up custom keywords
21:58:29.219 INFO blackrusemod.BlackRuseMod> done setting up custom keywords
21:58:29.219 INFO ThMod_FnH.ThMod> Setting up custom keywords
21:58:29.220 INFO ThMod_FnH.ThMod> Keywords setting finished.
21:58:31.829 INFO helpers.ImageMaster> Texture load time: 2608ms
21:58:31.934 INFO helpers.FontHelper> Font load time (Map Fonts): 32ms
21:58:32.298 INFO helpers.FontHelper> Font load time (Kreon Standard): 364ms
21:58:33.161 INFO helpers.FontHelper> Font load time (The rest of it): 862ms
21:58:33.171 INFO unlock.UnlockTracker> RED UNLOCKS:   0/9
21:58:33.176 INFO unlock.UnlockTracker> GREEN UNLOCKS: 3/9
21:58:33.176 INFO unlock.UnlockTracker> BLUE UNLOCKS: 0/9
21:58:33.177 INFO unlock.UnlockTracker> RELIC UNLOCKS: 3/18
21:58:33.277 INFO unlock.UnlockTracker> CARDS SEEN:    483/0
21:58:33.327 INFO unlock.UnlockTracker> RELICS SEEN:   130/0
21:58:33.328 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
21:58:33.329 INFO replayTheSpire.ReplayTheSpireMod> ReplayTheSpireMod | Loading Unlock Data...
21:58:33.331 INFO basemod.BaseMod> begin editing cards
21:58:33.332 INFO blackrusemod.BlackRuseMod> begin editting cards
21:58:33.333 INFO blackrusemod.BlackRuseMod> add cards for THE_SERVANT

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at blackrusemod.cards.KidneyShot.<init>(KidneyShot.java:32)
	at blackrusemod.BlackRuseMod.receiveEditCards(BlackRuseMod.java:326)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2162)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:284)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by kiooeht** [comment]
The Servant (BlackRuseMod) hasn't been updated to work with the latest versions of Slay the Spire and BaseMod. Disable it for now.
