### ISSUE TITLE
ASM compability problems

### ISSUE THREAD

**Issue by Jacky2611** [kiooeht/ModTheSpire#11]
I am having a few compability issues with some libraries I want to use in a mod. Quite a few of them require a modern-ish asm version. The problem is that ModTheSpire uses javautil, which in turn uses a really outdated asm version (3.3.1 I think).
The only solution I came up with so far would be to either use a seperate class loader to manage different asm versions or to build my own versions of all these libraries so that I can shadow asm, but to be honest I would rather avoid that.
Would it be possible to either update javautil or to use something else?

**Comment by kiooeht** [comment]
Unfortunately there's no newer version of javautil and it doesn't seem like it's going to be updated to use newer version of ASM anytime.
Javautil is currently being used to quickly search through all of the game's classes for certain things. I can rewrite that functionality myself using a newer version of ASM, but it will take some time.
I'm curious what libraries you're wanting to use that require ASM.

**Comment by Jacky2611** [comment]
There are quite a few libraries that depend on asm. The real problem is the MethodViewer class, which used to be an interface before version 4.
In theory I could probably switch out most of the problematic libraries, but I really want to use Kryo. (Serialization and Deserialization)

It might be possible to use something like JarJarLinks to automatically shadow javautils' dependencies. Would it be acceptable to add something like that to ModTheSpire's build configuration in case I somehow get it working?

**Comment by Jacky2611** [comment]
Got it working with jarjarlinks.

Adding the following to the projects's pom file makes sure that the asm version for javautil is put into a different package, which avoids conflicts with newer asm versions in mods.

`
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>jarjar-maven-plugin</artifactId>
                <version>1.9</version>
                <executions>
                    <execution>
                        <id>jarjar</id>
                        <goals><goal>jarjar</goal></goals>
                    </execution>
                </executions>
                <configuration>
                    <overwrite>true</overwrite>
                    <includes>
                        <include>*:asm*</include>
                    </includes>
                    <rules>
                        <rule>
                            <pattern>org.objectweb.asm.*</pattern>
                            <result>org.objectweb.shadow.asm.$@1</result>
                        </rule>
                        <rule>
                            <pattern>org.objectweb.asm.**.*</pattern>
                            <result>org.objectweb.shadow.asm.@1.$@2</result>
                        </rule>
                    </rules>
                </configuration>
            </plugin>`

**Comment by kiooeht** [comment]
Should that go before or after the shade plugin? Currently if I try to use jarjarlinks it seems to add ASM to the final jar twice. Once in `org.objectweb.asm` and once in `org.objectweb.shadow.asm`, but the shadow version contains significantly more. Is that intentional?

**Comment by Jacky2611** [comment]
After the shade plugin, which I only now realized was already in the pom. (I am an idiot)
Forget jarjarlinks, if maven shade is already in the pom we might as well use it to relocate the asm dependency.
Just insert the following lines directly after <minimizeJar>:

`                            <relocations>
                                <relocation>
                                    <pattern>org.objectweb.asm</pattern>
                                    <shadedPattern>org.shaded.objectweb.asm</shadedPattern>
                                </relocation>
                            </relocations>`

If memory serves me right this should do the job just fine.

**Comment by kiooeht** [comment]
I've added that to the pom (b0dd938669dfe7569a77b74f6b1c71031e2b1179), hopefully it does what you need.
