### ISSUE TITLE
unlisted mod not sure how to tell you this 

### ISSUE THREAD

**Issue by 5m1l35** [kiooeht/ModTheSpire#114]
https://github.com/Celicath/GathererMod/releases , https://github.com/HOYKJ/KomeijiMod/releases  and https://github.com/jonasdasdefekte/The-Sage/releases I believe komeiji should go in the outdated category but still think it should be added to the list. Sorry if this is annoying. Was not sure how to contact you about this. i dont know if you only list mods after being asked to?

**Comment by kiooeht** [comment]
I don't usually add mods to the list of mods. I leave it to the mod authors to add themselves to the list.
I've passed on the message to the authors so they can add themselves.
