### ISSUE TITLE
StsLib Problem

### ISSUE THREAD

**Issue by Squawkerz** [kiooeht/ModTheSpire#116]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
**Yes**

**Crash Log**
```
https://pastebin.com/QwwyuCy5
```

**Additional context**
There seems to be a problem with StsLib. All other mods work ok. I used to be able to play with it before but after an update it doesn't work.

**Comment by kiooeht** [comment]
You're Slay the Spire is about 3 weeks out of date. You're using version 10-18-2018. The latest is 11-08-2018.
