### ISSUE TITLE
Issue with windows command system 32?

### ISSUE THREAD

**Issue by tankdestroyer00** [kiooeht/ModTheSpire#117]
Yes I have read the troubleshooting thing

It says windows cannot find .jre\ bin\ javaw.exe make sure you typed it in correctly.

I have tried using running it in admin mode as well and still doesn't work pls help

**Comment by kiooeht** [comment]
Sounds like you're running it from the wrong place.

You should be running it from the SlayTheSpire install directory.

**Comment by tankdestroyer00** [comment]
i used the windows command prompt

**Comment by tankdestroyer00** [comment]
I am completely up to date on everything as well

**Comment by tankdestroyer00** [comment]
it was working just fine yesterday then all of a sudden it stopped working

**Comment by tankdestroyer00** [comment]
it seems to be working now for some reason... thx
