### ISSUE TITLE
ModTheSpire not starting.

### ISSUE THREAD

**Issue by Them8** [kiooeht/ModTheSpire#118]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
Yes
**Crash Log**
nothing if i try just starting mts.cmd or ModTheSpire.jar
If i actively try and start MTS.cmd as admin i get "could not find file .\jre\bin\javaw.exe control that you gve it the right name and try again"
if i actively select start ModTheSpire.jar with java(TM) platform SE binary i get "could not find desktop-1.0.jar even tho its right next to the file.

**Additional context**
When i open the MTS.cmd as admin the commnd lines say C;\WINDOWS\system32>start .\jre\bin\javaw.exe -jar .\ModTheSpire.jar
if i edit MTS.cmd in notepad so that the .\ points actively to the Slay the spire folder instead i get the "could not find desktop-1.0.jar" message.
i also have all my steam games in the D:\ Disk if that matters.

**Comment by kiooeht** [comment]
You shouldn't be starting `MTS.cmd` as admin. By the looks of it, doing so has the same issue as #19 where it gets run from from `C:\WINDOWS\system32` rather than the directory it's located in.

Just double-click `MTS.cmd` to run it normally.

**Comment by Them8** [comment]
as the first sentence if i just double click it nothing happens at all....

**Comment by patke-92** [comment]
Could you show us a "picture" (if real picture or written down just to show does not matter) of your Slay the Spire folder?

**Comment by Them8** [comment]
![slaythespire](https://user-images.githubusercontent.com/45337294/48984760-45e91f80-f100-11e8-9e1a-240822ab3dcb.PNG)
![cmd error](https://user-images.githubusercontent.com/45337294/48984764-48e41000-f100-11e8-8bfb-34ef54015a7c.PNG)
![java open error](https://user-images.githubusercontent.com/45337294/48984765-4bdf0080-f100-11e8-9f65-5442795426d7.PNG)

**Comment by Them8** [comment]
![powershellslay](https://user-images.githubusercontent.com/45337294/48984896-fc013900-f101-11e8-9c32-a5693d30085f.PNG)
it Just goes like this and nothing else happens.
and there is a file called javaw.exe in the bin folder.

**Comment by kiooeht** [comment]
Change that command to `.\jre\bin\java.exe -jar .\ModTheSpire.jar`
(Remove `start`, change `javaw` to `java`)

**Comment by Them8** [comment]
Nothing opend but.
![progress](https://user-images.githubusercontent.com/45337294/48984960-ae390080-f102-11e8-923d-10657ab34e77.PNG)

**Comment by patke-92** [comment]
Could you cut every mod except basemod out of /mods and try starting again? This new error could be one of your mods screwing something up.

**Comment by Them8** [comment]
Now it opens from Powershell!

**Comment by kiooeht** [comment]
That log points to GluttonMod making a release with a bad version number in it. Update to the latest version manually (https://github.com/HypoSoc/GluttonMod/releases). See if that fixes it.

**Comment by Them8** [comment]
Now it Works!!! Thank you everyone!
Keep up the exelent work you are doing!
