### ISSUE TITLE
Custom Game Character List Doesn't Wrap

### ISSUE THREAD

**Issue by imakunee** [kiooeht/ModTheSpire#120]
Dunno if this is a BaseMod issue or not. I'll post in both.

https://i.imgur.com/Wwl5atY.png

Should be pretty self explanatory. With many characters installed, the character list in custom games just stretches on and on until off the screen. Perhaps it should wrap or have the left right arrows like the normal run does. Thank you very much!

**Comment by kiooeht** [comment]
This is a BaseMod issue.
