### ISSUE TITLE
Mods causing issues?

### ISSUE THREAD

**Issue by tankdestroyer00** [kiooeht/ModTheSpire#121]
it seems with these mods enabled that the game automatically closes 

![screenshot 4](https://user-images.githubusercontent.com/45301105/49332755-cab0bf00-f580-11e8-9a89-e0c173009f45.png)

I don't know which one/s is causing problems pls help

**Comment by tankdestroyer00** [comment]
![screenshot 5](https://user-images.githubusercontent.com/45301105/49333697-73671a80-f591-11e8-89c2-85fbeb7df980.png)

**Comment by kiooeht** [comment]
There's no error in that part of the log. Scroll up until you see something that looks like an error.

**Comment by tankdestroyer00** [comment]
![screenshot 6](https://user-images.githubusercontent.com/45301105/49334383-e3ca6780-f5a2-11e8-9b91-257756389f6c.png)

**Comment by kiooeht** [comment]
Looks like a problem with the Glutton mod.

**Comment by tankdestroyer00** [comment]
can you ask the creator of the glutton and witch mod to fix their things so I can use them both in the future please.

**Comment by tankdestroyer00** [comment]
![screenshot 7](https://user-images.githubusercontent.com/45301105/49334644-d4e6b380-f5a8-11e8-9e21-d3de03aa75fa.png)

**Comment by tankdestroyer00** [comment]
new error

**Comment by tankdestroyer00** [comment]
I disabled witch mod still had this error

**Comment by tankdestroyer00** [comment]
So I can use all my mods

**Comment by kiooeht** [comment]
You would have to upgrade your computer. RAM/VRAM is your computer's memory, you have to upgrade it to get more.

**Comment by tankdestroyer00** [comment]
how to do that?

**Comment by tankdestroyer00** [comment]
im on latest version of Windows 10

**Comment by tankdestroyer00** [comment]
I have 5.89 Gigabytes of RAM avaible

**Comment by tankdestroyer00** [comment]
![screenshot 9](https://user-images.githubusercontent.com/45301105/49335462-d9689780-f5bb-11e8-9f5e-b4e1f54429a2.png)

**Comment by tankdestroyer00** [comment]
…and this one.
