### ISSUE TITLE
Windows cannot find .\jre\bin\javaw.exe

### ISSUE THREAD

**Issue by watercolorhearts** [kiooeht/ModTheSpire#126]
This is on Windows 7 64-bit. Pictured below: 
![screenshot_1](https://user-images.githubusercontent.com/32391190/49948075-b0e87380-fec0-11e8-8fc6-109ebaeb69ee.png)

**Comment by kiooeht** [comment]
You're trying to run that command from the wrong place.

You're trying to run it from `C:\Windows\system32` but you need to run it from your Slay the Spire install directory.

**Comment by LeoRandi** [comment]
And where's that?

**Comment by kiooeht** [comment]
This issue is old, with Steam Workshop it is no longer an issue.
