### ISSUE TITLE
More elaborate explanation for setup / installation

### ISSUE THREAD

**Issue by BalticBytes** [kiooeht/ModTheSpire#13]
I can not get anything to work with the combined documentation on installation / setup from ModTheSpire or BaseMod. Please provide a more friendly step by step instruction on how to actually start coding. 

(I have no experience with maven or modding)

**Comment by VoodooPuppet** [comment]
just download the jar file - https://github.com/kiooeht/ModTheSpire/releases
add it to your SlayTheSpire folder
Now make another folder called "mods" add the mods you want in their.
All you need to do now is Click on the ModTheSpire.jar and select the mods you want to play with

**Comment by Chst8754** [comment]
What about the "how to actually start coding" part?

**Comment by daviscook477** [comment]
I may try to explain how to setup everything to work with Eclipse + Maven. What exactly are you looking for in a how to start coding mods guide @Chst8754?

**Comment by Chst8754** [comment]
Well a step by step (potentially with pictures) would be awesome.
Whenever a step contains something that could be unclear to some people (like me) then that could be explained as well.

Otherwise really just the basic setup, until I can start writing code.
@daviscook477
