### ISSUE TITLE
Infinitespire find dependency

### ISSUE THREAD

**Issue by franzlucas** [kiooeht/ModTheSpire#132]
ERROR: Unable to find dependency 'stslib' for mod 'infinitespire'.

![update](https://user-images.githubusercontent.com/42304237/50735227-5522b900-11e6-11e9-89bd-217249c15a2b.JPG)

**Comment by kiooeht** [comment]
You need to get the mod StSLib and enable it.

You should switch over to using the [Steam Workshop](https://steamcommunity.com/workshop/browse/?appid=646570). Now that Workshop support is official, all future updates are available there instead of GitHub.
