### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by WNJStudio** [kiooeht/ModTheSpire#133]
Maybe a special case, but i found out that MTS causes the java.exe process to use over 3~4 GB of memory

**Comment by kiooeht** [comment]
What and how many mods are you using?

If you're using a lot of mods, they're all loading their art and other resources. That adds up.

**Comment by WNJStudio** [comment]
Nah,you can close the issue, found out that sts itself that leaks, using over 3 gigs on normal mode

**Comment by WNJStudio** [comment]
Found out where was the issue with the leaking memory on normal mode, solved by upgrading graphics driver, but still, MTS won't run on the GPU so it leaks a lot of RAM, today it reached 10 GIGS of usage

**Comment by WNJStudio** [comment]
Tried the following and it seems to work, since i found out that mts-launcher.jar is just a wrapper of ModTheSpire.jar, and renaming mts-launcher.jar to desktop-1.0.jar won't work, I copied ModTheSpire.jar from the Workshop dir to the Game dir, renamed it, and launched via SlayTheSpire.exe which i forced to run on the gpu.
Memory 1.7 GB at startup, need more testing, but it's better than before when i had 3.5 GB at startup
