### ISSUE TITLE
Why it tells me use ModTheSpire.jar if the download is a .zip?

### ISSUE THREAD

**Issue by LeoRandi** [kiooeht/ModTheSpire#135]
Idk if its just a download problem, or if the .jar file its inside the .zip, but i cant find it, neither use it. I also tried to convert the .zip to .jar  and then followed the instructions, but it isnt working.

**Comment by kiooeht** [comment]
You shouldn't be downloading the zip anymore. Use the Steam Workshop (https://steamcommunity.com/sharedfiles/filedetails/?id=1605060445) for ModTheSpire and all mods.
