### ISSUE TITLE
Mods arent playable

### ISSUE THREAD

**Issue by thesevenceas** [kiooeht/ModTheSpire#139]
Mods are recognized in the mods page however none of the actual mods are playable in the game

**Comment by kiooeht** [comment]
Are you marking them checked? You need to mark the checkboxes of the mods you want to play with.

![java_2019-01-21_21-46-55](https://user-images.githubusercontent.com/236842/51514772-17b55280-1dc6-11e9-8248-7abffaf4c4c1.png)

**Comment by AvangionQ** [comment]
Same problem:
The Gatherer requires Mod the Spire 3.7.0 (current version is 3.6.3)
Jugger Mod has a missing version number (no idea what this is)
The Sage also requires Mod the Spire 3.8.3
The Administrix requires Mod the Spire 3.7.4

**Comment by kiooeht** [comment]
@AvangionQ You need to get a newer version of MTS. On January 3rd Slay the Spire added official Steam Workshop support and all releases since then have been available on the workshop.
https://steamcommunity.com/sharedfiles/filedetails/?id=1605060445
