### ISSUE TITLE
How to access private instance members from a patch method?

### ISSUE THREAD

**Issue by GregRos** [kiooeht/ModTheSpire#152]
First of all, I'd like to say good job on this framework! I've written something similar myself for .NET, a while back. I haven't touched it in a long while, but maybe you can get some inspiration from it. It's really similar in lots of ways, though I went a bit further in some respects. https://github.com/GregRos/Patchwork

By the way, I've actually decided to write my mod in Kotlin, and it's working out great (I kind of dislike Java).

Anyway, to my question - when I patch a method, how do I access private and protected instance members in my code?

**Comment by kiooeht** [comment]
You need to look into something called "reflection". It will let you access private and protected member variables and methods.

**Comment by GregRos** [comment]
Ah, I see. Yeah, I know what reflection is (I wrote a damn framework for this stuff, after all). I thought there was a better way - the code you're writing will be injected into the method call, after all.

**Comment by kiooeht** [comment]
Ah, you're misunderstanding how patching works. It doesn't inject the code you write, it injects a call to the patch function you wrote.
