### ISSUE TITLE
Better error when steam is not running

### ISSUE THREAD

**Issue by alexdriedger** [kiooeht/ModTheSpire#154]
## Problem

If you run MTS without Steam running, MTS crashes and you get an error that seems unrelated to Steam. This can be confusing if you have not encountered this error before (eg. new to modding development).

## Proposed Solution
MTS should check if Steam is running and if Steam is not, throw an error suggesting the user checking if steam is running

## Current Behavior
```java
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetColorSpecificCardSwitch:
No method [getColorSpecificCard(com.megacrit.cardcrawl.characters.AbstractPlayer$PlayerClass, com.megacrit.cardcrawl.random.Random)] found on
class [com.megacrit.cardcrawl.helpers.CardLibrary]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:344)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:252)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:330)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:265)
	at java.lang.Thread.run(Thread.java:745)
```

## Desired Behavior

```java
ModTheSpire cannot connect to Steam.

Please ensure Steam is running on your computer and trying running ModTheSpire again

Closing ModTheSpire.....
```

**Comment by kiooeht** [comment]
You are not getting an error that _seems_ unrelated, you are getting an error that _is_ unrelated.

If you run MTS without Steam running, there is no error or crash, MTS launches fine, it just won't have any workshop mods in the list. Your error is completely unrelated.
