### ISSUE TITLE
Caused by: compile error: no such field

### ISSUE THREAD

**Issue by Poons12** [kiooeht/ModTheSpire#164]
I honestly don't know what the issue is anymore, maybe its Java related? I tried everything, it gives the same error.
ModVersion Info:

 - Java version (1.8.0_221)
 - Slay the Spire (07-17-2019)
 - ModTheSpire (3.11.0)
Mod list:
 - basemod (5.5.0)
 - StrawberrySpire (0.4.3)
 - stslib (1.10.0)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
Patching Overrides...
Class: [basemod.abstracts.CustomMonster]
 - Overriding [com.megacrit.cardcrawl.monsters.AbstractMonster.renderDamageRange(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
      Fixing invocations in superclass AbstractMonster...
        @ 932
      Replacing SpireSuper calls...
        @ 127
 { super.renderDamageRange(((com.badlogic.gdx.graphics.g2d.SpriteBatch) $1[0]));
$_ = null; }
 - Overriding [com.megacrit.cardcrawl.monsters.AbstractMonster.renderIntentVfxBehind(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
      Fixing invocations in superclass AbstractMonster...
        @ 929
      Replacing SpireSuper calls...
        @ 133
 { super.renderIntentVfxBehind(((com.badlogic.gdx.graphics.g2d.SpriteBatch) $1[0]));
$_ = null; }
 - Overriding [com.megacrit.cardcrawl.monsters.AbstractMonster.renderIntent(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
      Fixing invocations in superclass AbstractMonster...
        @ 930
      Replacing SpireSuper calls...
        @ 139
 { super.renderIntent(((com.badlogic.gdx.graphics.g2d.SpriteBatch) $1[0]));
$_ = null; }
 - Overriding [com.megacrit.cardcrawl.monsters.AbstractMonster.renderIntentVfxAfter(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
      Fixing invocations in superclass AbstractMonster...
        @ 931
      Replacing SpireSuper calls...
        @ 145
 { super.renderIntentVfxAfter(((com.badlogic.gdx.graphics.g2d.SpriteBatch) $1[0]));
$_ = null; }
 - Overriding [com.megacrit.cardcrawl.monsters.AbstractMonster.renderName(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
      Fixing invocations in superclass AbstractMonster...
        @ 943
      Replacing SpireSuper calls...
        @ 151
 { super.renderName(((com.badlogic.gdx.graphics.g2d.SpriteBatch) $1[0]));
$_ = null; }
Injecting patches...

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.ShrinkLongDescription$Scale]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Float descriptionScale_988;
{
if (descriptionScale == null) { descriptionScale = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
descriptionScale.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "descriptionScale_988");
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.MaxHandSizePatch$SaveField]
 - Patching [com.megacrit.cardcrawl.saveAndContinue.SaveFile]
 - Adding Field: public java.lang.Integer maxHandSize_808;
   - Copying annotation: @com.google.gson.annotations.SerializedName(value="basemod:max_hand_size")
{
if (maxHandSize == null) { maxHandSize = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
maxHandSize.initialize(com.megacrit.cardcrawl.saveAndContinue.SaveFile.class, "maxHandSize_808");
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveFile.ModSaves]
 - Patching [com.megacrit.cardcrawl.saveAndContinue.SaveFile]
 - Adding Field: public basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveFile.ModSaves$HashMapOfJsonElement modSaves_258;
   - Copying annotation: @com.google.gson.annotations.SerializedName(value="basemod:mod_saves")
{
if (modSaves == null) { modSaves = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
modSaves.initialize(com.megacrit.cardcrawl.saveAndContinue.SaveFile.class, "modSaves_258");
}
 - Adding Field: public basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveFile.ModSaves$ArrayListOfJsonElement modCardSaves_369;
   - Copying annotation: @com.google.gson.annotations.SerializedName(value="basemod:mod_card_saves")
{
if (modCardSaves == null) { modCardSaves = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
modCardSaves.initialize(com.megacrit.cardcrawl.saveAndContinue.SaveFile.class, "modCardSaves_369");
}
 - Adding Field: public basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveFile.ModSaves$ArrayListOfJsonElement modRelicSaves_838;
   - Copying annotation: @com.google.gson.annotations.SerializedName(value="basemod:mod_relic_saves")
{
if (modRelicSaves == null) { modRelicSaves = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
modRelicSaves.initialize(com.megacrit.cardcrawl.saveAndContinue.SaveFile.class, "modRelicSaves_838");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.RefundFields]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Integer refund_928;
{
if (refund == null) { refund = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
refund.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "refund_928");
}
 - Adding Field: public java.lang.Integer baseRefund_115;
{
if (baseRefund == null) { baseRefund = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
baseRefund.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "baseRefund_115");
}
 - Adding Field: public java.lang.Boolean isRefundUpgraded_478;
{
if (isRefundUpgraded == null) { isRefundUpgraded = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
isRefundUpgraded.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "isRefundUpgraded_478");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.SoulboundField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean soulbound_435;
{
if (soulbound == null) { soulbound = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
soulbound.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "soulbound_435");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.ExhaustiveField$ExhaustiveFields]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Integer exhaustive_869;
{
if (exhaustive == null) { exhaustive = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
exhaustive.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "exhaustive_869");
}
 - Adding Field: public java.lang.Integer baseExhaustive_487;
{
if (baseExhaustive == null) { baseExhaustive = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
baseExhaustive.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "baseExhaustive_487");
}
 - Adding Field: public java.lang.Boolean isExhaustiveUpgraded_368;
{
if (isExhaustiveUpgraded == null) { isExhaustiveUpgraded = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
isExhaustiveUpgraded.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "isExhaustiveUpgraded_368");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.SneckoField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean snecko_703;
{
if (snecko == null) { snecko = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
snecko.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "snecko_703");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.patches.core.AbstractCreature.TempHPField]
 - Patching [com.megacrit.cardcrawl.core.AbstractCreature]
 - Adding Field: public java.lang.Integer tempHp_737;
{
if (tempHp == null) { tempHp = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
tempHp.initialize(com.megacrit.cardcrawl.core.AbstractCreature.class, "tempHp_737");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.AlwaysRetainField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean alwaysRetain_57;
{
if (alwaysRetain == null) { alwaysRetain = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
alwaysRetain.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "alwaysRetain_57");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.GraveField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean grave_564;
{
if (grave == null) { grave = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
grave.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "grave_564");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.patches.HitboxRightClick]
 - Patching [com.megacrit.cardcrawl.helpers.Hitbox]
 - Adding Field: public java.lang.Boolean rightClicked_398;
{
if (rightClicked == null) { rightClicked = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
rightClicked.initialize(com.megacrit.cardcrawl.helpers.Hitbox.class, "rightClicked_398");
}
 - Adding Field: public java.lang.Boolean rightClickStarted_451;
{
if (rightClickStarted == null) { rightClickStarted = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
rightClickStarted.initialize(com.megacrit.cardcrawl.helpers.Hitbox.class, "rightClickStarted_451");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.FleetingField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean fleeting_971;
{
if (fleeting == null) { fleeting = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
fleeting.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "fleeting_971");
}

Patch Class: [com.evacipated.cardcrawl.mod.stslib.fields.cards.AbstractCard.AutoplayField]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard]
 - Adding Field: public java.lang.Boolean autoplay_8;
{
if (autoplay == null) { autoplay = new com.evacipated.cardcrawl.modthespire.lib.SpireField(null); }
autoplay.initialize(com.megacrit.cardcrawl.cards.AbstractCard.class, "autoplay_8");
}

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.modsscreen.SaveBaseModBadges]
 - Patching [basemod.BaseMod.registerModBadge(com.badlogic.gdx.graphics.Texture,java.lang.String,java.lang.String,java.lang.String,basemod.ModPanel)]
 - Adding Insert @ r8 (abs:699)...

{
com.evacipated.cardcrawl.modthespire.patches.modsscreen.SaveBaseModBadges.Insert($$, badge);
}

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit]
 - Patching [com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()]
 - Adding Insert @ 248...

{
com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit.Insert($0, $$);
}

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
 - Patching [com.megacrit.cardcrawl.credits.CreditsScreen()]
 - Adding Insert @ r5 (abs:56)...

{
float[] __tmpY = new float[1];
__tmpY[0] = tmpY;
com.evacipated.cardcrawl.modthespire.patches.CreditsModList.Insert($0, $$, __tmpY);
tmpY = __tmpY[0];
}

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem]
 - Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.setMainMenuButtons()]
 - Adding Insert @ r4 (abs:145)...

{
int[] __index = new int[1];
__index[0] = index;
com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem.Insert($0, $$, __index);
index = __index[0];
}

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.TopPanelModList$Render]
 - Patching [com.megacrit.cardcrawl.ui.panels.TopPanel.render(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
 - Adding Insert @ 1089...

{
com.evacipated.cardcrawl.modthespire.patches.TopPanelModList$Render.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$ApplyPowersMulti]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard.applyPowers()]
 - Adding Insert @ r69 (abs:2996)...

{
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$ApplyPowersMulti.Insert($0, $$, tmp);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.CustomCardsPatch]
 - Patching [com.megacrit.cardcrawl.helpers.CardLibrary.initialize()]
 - Adding Insert @ 329...

{
basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.CustomCardsPatch.Insert($$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.OnPlayerLoseBlockToggle]
 - Patching [com.megacrit.cardcrawl.actions.GameActionManager.getNextAction()]
 - Adding Insert @ 392...

{
basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.OnPlayerLoseBlockToggle.InsertPost($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.MissingPortraitFix]
 - Patching [com.megacrit.cardcrawl.screens.SingleCardViewPopup.renderPortrait(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
 - Adding Insert @ 560...

{
com.evacipated.cardcrawl.modthespire.lib.SpireReturn opt = basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.MissingPortraitFix.Insert($0, $$, card);
if (opt.isPresent()) { return; }
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.relics.AbstractRelic.InstantObtainRelicGetHook]
 - Patching [com.megacrit.cardcrawl.relics.AbstractRelic.instantObtain(com.megacrit.cardcrawl.characters.AbstractPlayer,int,boolean)]
 - Adding Insert @ r2 (abs:220)...

{
basemod.patches.com.megacrit.cardcrawl.relics.AbstractRelic.InstantObtainRelicGetHook.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.core.EnergyManager.PostEnergyRechargeHook]
 - Patching [com.megacrit.cardcrawl.core.EnergyManager.recharge()]
 - Adding Insert @ 47...

{
basemod.patches.com.megacrit.cardcrawl.core.EnergyManager.PostEnergyRechargeHook.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.CardGroup.MoveToExhaustPileHook]
 - Patching [com.megacrit.cardcrawl.cards.CardGroup.moveToExhaustPile(com.megacrit.cardcrawl.cards.AbstractCard)]
 - Adding Insert @ r6 (abs:928)...

{
basemod.patches.com.megacrit.cardcrawl.cards.CardGroup.MoveToExhaustPileHook.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$CalculateCardDamage]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard.calculateCardDamage(com.megacrit.cardcrawl.monsters.AbstractMonster)]
 - Adding Insert @ r7 (abs:3050)...

{
float[] __tmp = new float[1];
__tmp[0] = tmp;
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$CalculateCardDamage.Insert($0, $$, __tmp);
tmp = __tmp[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.MaxHandSizePatch$Load]
 - Patching [com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(com.megacrit.cardcrawl.characters.AbstractPlayer)]
 - Adding Insert @ 1083...

{
basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.MaxHandSizePatch$Load.Insert($0, $$, saveFile);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.OnPlayerLoseBlockToggle]
 - Patching [com.megacrit.cardcrawl.actions.GameActionManager.getNextAction()]
 - Adding Insert @ 383...

{
basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.OnPlayerLoseBlockToggle.InsertPre($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.ui.panels.PotionPopUp.PrePotionUseHookTargetMode]
 - Patching [com.megacrit.cardcrawl.ui.panels.PotionPopUp.updateTargetMode()]
 - Adding Insert @ 246...

{
basemod.patches.com.megacrit.cardcrawl.ui.panels.PotionPopUp.PrePotionUseHookTargetMode.Insert($0, $$, potion);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.GetNextActionHook]
 - Patching [com.megacrit.cardcrawl.actions.GameActionManager.getNextAction()]
 - Adding Insert @ 247...

{
basemod.patches.com.megacrit.cardcrawl.actions.GameActionManager.GetNextActionHook.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterRelicsHookSwitch]
 - Patching [com.megacrit.cardcrawl.characters.AbstractPlayer.initializeStarterRelics(com.megacrit.cardcrawl.characters.AbstractPlayer$PlayerClass)]
 - Adding Insert @ r14 (abs:458)...

{
java.util.ArrayList[] __relics = new java.util.ArrayList[1];
__relics[0] = relics;
basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterRelicsHookSwitch.Insert($0, $$, __relics);
relics = __relics[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.events.BackToBasics.UpgradeStrikeAndDefends]
 - Patching [com.megacrit.cardcrawl.events.city.BackToBasics.upgradeStrikeAndDefends()]
 - Adding Insert @ r30 (abs:135)...

{
basemod.patches.com.megacrit.cardcrawl.events.BackToBasics.UpgradeStrikeAndDefends.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.ui.panels.TopPanel.TopPanelPatches$SetPlayerNamePatch]
 - Patching [com.megacrit.cardcrawl.ui.panels.TopPanel.setPlayerName()]
 - Adding Insert @ 190...

{
basemod.patches.com.megacrit.cardcrawl.ui.panels.TopPanel.TopPanelPatches$SetPlayerNamePatch.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.custom.CustomModeScreen.InitializeCharacterButtons]
 - Patching [com.megacrit.cardcrawl.screens.custom.CustomModeScreen.initializeCharacters()]
 - Adding Insert @ 254...

{
basemod.patches.com.megacrit.cardcrawl.screens.custom.CustomModeScreen.InitializeCharacterButtons.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderDescriptionEnergy$AlterTmp]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard.renderDescription(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
 - Adding Insert @ r31 (abs:1980)...

{
java.lang.String[] __tmp = new java.lang.String[1];
__tmp[0] = tmp;
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderDescriptionEnergy$AlterTmp.Insert($0, $$, __tmp);
tmp = __tmp[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue.Save]
 - Patching [com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue.save(com.megacrit.cardcrawl.saveAndContinue.SaveFile)]
 - Adding Insert @ 302...

{
basemod.patches.com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue.Save.Insert($$, params);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar.ColorTabBarFix$Render]
 - Patching [com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar.render(com.badlogic.gdx.graphics.g2d.SpriteBatch,float)]
 - Adding Insert @ 183...

{
basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar.ColorTabBarFix$Render.Insert($0, $$, curTab);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.core.AbstractCreature.PlayerMaxHPChange$Decrease]
 - Patching [com.megacrit.cardcrawl.core.AbstractCreature.decreaseMaxHealth(int)]
 - Adding Insert @ 230...

{
int[] __amount = new int[1];
__amount[0] = amount;
com.evacipated.cardcrawl.modthespire.lib.SpireReturn opt = basemod.patches.com.megacrit.cardcrawl.core.AbstractCreature.PlayerMaxHPChange$Decrease.Insert($0, $$, __amount);
amount = __amount[0];
if (opt.isPresent()) { return; }
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.helpers.TipHelper.FakeKeywords]
 - Patching [com.megacrit.cardcrawl.helpers.TipHelper.renderKeywords(float,float,com.badlogic.gdx.graphics.g2d.SpriteBatch,java.util.ArrayList)]
 - Adding Insert @ r0 (abs:263)...

{
float[] __y = new float[1];
__y[0] = y;
basemod.patches.com.megacrit.cardcrawl.helpers.TipHelper.FakeKeywords.Insert($$, __y, card);
y = __y[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetCardListSwitch]
 - Patching [com.megacrit.cardcrawl.helpers.CardLibrary.getCardList(com.megacrit.cardcrawl.helpers.CardLibrary$LibraryType)]
 - Adding Insert @ r45 (abs:1047)...

{
basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetCardListSwitch.Insert($$, retVal);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.ui.panels.PotionPopUp.PostPotionUseHookTargetMode]
 - Patching [com.megacrit.cardcrawl.ui.panels.PotionPopUp.updateTargetMode()]
 - Adding Insert @ 251...

{
basemod.patches.com.megacrit.cardcrawl.ui.panels.PotionPopUp.PostPotionUseHookTargetMode.Insert($0, $$, potion);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.ShrinkLongDescription$ShiftSizeLineDescription]
 - Patching [com.megacrit.cardcrawl.screens.SingleCardViewPopup.renderDescription(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
 - Adding Insert @ 1019...

{
float[] __draw_y = new float[1];
__draw_y[0] = draw_y;
com.badlogic.gdx.graphics.g2d.BitmapFont[] __font = new com.badlogic.gdx.graphics.g2d.BitmapFont[1];
__font[0] = font;
float[] __current_x = new float[1];
__current_x[0] = current_x;
basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.ShrinkLongDescription$ShiftSizeLineDescription.Insert($0, $$, card, __draw_y, __font, __current_x);
draw_y = __draw_y[0];
font = __font[0];
current_x = __current_x[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHooks$PostRenderHook]
 - Patching [com.megacrit.cardcrawl.core.CardCrawlGame.render()]
 - Adding Insert @ 488...

{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHooks$PostRenderHook.Insert($0, $$, sb);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.CustomBosses$Ascension20DoubleBoss]
 - Patching [com.megacrit.cardcrawl.ui.buttons.ProceedButton.update()]
 - Adding Insert @ 116...

{
basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.CustomBosses$Ascension20DoubleBoss.Insert($0, $$);
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$ApplyPowers]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard.applyPowers()]
 - Adding Insert @ r19 (abs:2946)...

{
float[] __tmp = new float[1];
__tmp[0] = tmp;
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$ApplyPowers.Insert($0, $$, __tmp);
tmp = __tmp[0];
}

Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.SwapCharacterSelectScreen]
 - Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen(boolean)]
 - Adding Insert @ 132...

{
basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.SwapCharacterSelectScreen.Insert($0, $$);
}

Patch Class: [basemod.patches.whatmod.PlayerPowerTips]
 - Patching [com.megacrit.cardcrawl.core.AbstractCreature.renderPowerTips(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
 - Adding Insert @ r2 (abs:819)...

{
basemod.patches.whatmod.PlayerPowerTips.Insert($0, $$, p);
}
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: javassist.CannotCompileException: [source error] no such field: p
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:224)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:217)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:342)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:265)
	at java.lang.Thread.run(Unknown Source)
Caused by: javassist.CannotCompileException: [source error] no such field: p
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:198)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:222)
	... 4 more
Caused by: compile error: no such field: p
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by kiooeht** [comment]
You're running very old versions of BaseMod and StSLib (and probably your other mods too).
You should get your mods from the [Steam Workshop](https://steamcommunity.com/app/646570/workshop/).
If you don't have a Steam copy of Slay the Spire, you can download mods via https://beta.steamworkshopdownloader.io
