### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by IamCarbonMan** [kiooeht/ModTheSpire#17]
I'm trying to start the game through ModTheSpire, but clicking Play brings up the log window and then does nothing. An example log:

```
Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.
Setting isModded = true...Done.
Adding ModTheSpire to version...Done.
Initializing mods...
libgdx version 1.9.5
20:41:15.798 INFO basemod.BaseMod> initializeGson
20:41:15.814 INFO basemod.BaseMod> initializeTypeMaps
Done.
Starting game...
```

But the game never starts, nothing happens after this.

**Comment by kiooeht** [comment]
Since you got your problem fixed on the discord, I'm closing this.

**Comment by IamCarbonMan** [comment]
For anyone who stumbles on this and is having trouble: be sure ModTheSpire is unticked before clicking Play.
