### ISSUE TITLE
SteamDeck update Troble

### ISSUE THREAD

**Issue by Lorenbeil** [kiooeht/ModTheSpire#192]
ModTheSpire(v3.30.1) 업데이트 후 스팀덱에서 SuperFastMode와 문제를 일으킵니다.
SuperFastMode 활성시 게임의 진행이 불가능하게 느려집니다.

Sorry, I can't speak english (Google Translate)

Problems with SuperFastMode on Steam decks after ModTheSpire update(v3.30.1).
When SuperFastMode is enabled, game progress becomes unbearably slow.

Image : https://imgur.com/a/afNrpwg

**Comment by Skrelpoid** [comment]
Hello Lorenbeil, this was fixed with v1.0.8 in SuperFastMode.
Just wait some minutes and then the new Version should automatically be downloaded from the workshop.

**Comment by Lorenbeil** [comment]
thanks!

**Comment by Lorenbeil** [comment]
에러는 사라졌습니다.
하지만 스팀덱에서 게임이 빨라지지 않습니다

The error is gone.
But no speed up on steam decks

**Comment by Lorenbeil** [comment]
에러는 사라졌습니다.
하지만 스팀덱에서 게임이 빨라지지 않습니다

The error is gone.
But the game doesn't speed up on steam decks

**Comment by Skrelpoid** [comment]
Hmm that is weird. I checked and it seemed to be sped up for me.

@kiooeht , is there any difference between steamdeck and --imgui?

**Comment by Lorenbeil** [comment]
PC에선 정상적으로 빨라집니다.
하지만 스팀덱에선 속도업 1,000%도 아무런 변화가 없다.

Make some Actions instant <- 는 정상작동 합니다

On PC it runs normally.
However, in the Steam deck, even a 1,000% speed-up does not change anything.

Make some Actions instant <- works fine

**Comment by Skrelpoid** [comment]
Hi @Lorenbeil ,

I have analyzed the issue and have come to the following conclusion:
I mistyped something in the fix of this error which caused the speedup to not work.
I have fixed this in v1.0.9 in SuperFastMode, which should be automatically downloaded from the workshop for you.
Please let me know if the mod now works as expected on Steam Deck.

**Comment by Lorenbeil** [comment]
It works fine on Steam Deck
thank you!
