### ISSUE TITLE
[Suggestion] : Path the game only one time

### ISSUE THREAD

**Issue by Ayora29** [kiooeht/ModTheSpire#194]
Hello,
Is it technically possible to make mod the spire patching the game only one time?
I mean generate an executable jar that contains Slay the spire + all the desired mods.
Currently we need to patch the game each time we want to play...
Thanks.

**Comment by kiooeht** [comment]
This feature already exists, just somewhat hidden away. If you run ModTheSpire with the `--package` flag it will package up StS and your chosen mods into `desktop-1.0-modded.jar` which can be run standalone. It was made for the [standalone version of Downfall](https://store.steampowered.com/app/1865780/Downfall__A_Slay_the_Spire_Fan_Expansion/).

You would have to rerun it any time any mod got updated as the prepackaged version is a static copy of the mods at the time you ran the command.

**Comment by francois-renault** [comment]
Awesome :) Thanks
