### ISSUE TITLE
Running newer version of java trows error

### ISSUE THREAD

**Issue by Smeagol001** [kiooeht/ModTheSpire#22]
![image](https://user-images.githubusercontent.com/13831373/38149177-d401cbf0-3459-11e8-9990-6fba40353285.png)
 and  why shopuld i have to install an older version  were jave is unistalling old ones when updating...

**Comment by kiooeht** [comment]
ModTheSpire does not work with Java 9 or newer because Java 9 moved some parts of the java libraries that ModTheSpire needs. To support Java 9 would require either a separate build of ModTheSpire or not supporting Java 8. Slay the Spire uses Java 8, so I'd rather stick with just Java 8 support.

**Comment by Smeagol001** [comment]
soo when you auto update java its going to update to 9 anyways though


2018-03-30 22:48 GMT+02:00 Kiooeht <notifications@github.com>:

**Comment by daviscook477** [comment]
So don't auto update Java?

**Comment by kiooeht** [comment]
Java 8 shouldn't auto update to 9 (https://stackoverflow.com/a/45976717).

Plus you can have both 8 and 9 installed at once.
