### ISSUE TITLE
UI size is wrong on the logger

### ISSUE THREAD

**Issue by daviscook477** [kiooeht/ModTheSpire#24]
<img width="356" alt="bad_scroll_bars" src="https://user-images.githubusercontent.com/10566967/38177666-0f43f22c-35d3-11e8-8dd9-afc9579188a9.png">

**Comment by kiooeht** [comment]
It's not wrong, if you scroll to the right and scroll through the log, you'll find at least one really long line.

![java_2018-04-01_14-52-15](https://user-images.githubusercontent.com/236842/38177890-7fded144-35bc-11e8-93e3-12c7c2d0f672.png)

**Comment by daviscook477** [comment]
Okay fine. Maybe it's not technically **wrong** per say. But we have no way to permanently resize this window or have it scale properly. So **every** time you run in debug mode the scroll bar is off. I wasn't saying you needed to fix it. Just wanted to document the problem.
