### ISSUE TITLE
Incorrect line-endings in MTS.sh

### ISSUE THREAD

**Issue by Sheldan** [kiooeht/ModTheSpire#31]
I downloaded the latest release and with this release a shell script comes which is wrapper for executing the .jar file. 

According to the documentation, you only need to set the executable bit for this file and start it, but the shell script is not executable on Linux, because it contains the wrong line-endings.

It fails with the error `bash: ./MTS.sh: /bin/sh^M: bad interpreter: No such file or directory`.

 Executing `dos2unix` fixes this issue, but it would be great, that this would come out of the box.

**Comment by kiooeht** [comment]
This should now be fixed for future releases (https://github.com/kiooeht/ModTheSpire/commit/74db6e6abccc8a6618a6c0f1af36c03c5830b27a).
