### ISSUE TITLE
Patch 23

### ISSUE THREAD

**Issue by Neopergoss** [kiooeht/ModTheSpire#40]
Does betamode still work for patch 23?

**Comment by kiooeht** [comment]
If by betamode you mean this mod (https://github.com/timeracers/BetaMode/releases), it should as the only thing it does is set the beta flag in game. You should ask there to be sure.

However, all it does is enable the beta flag, it does not give you access to any beta content that is only in the beta branch, only beta content in the stable branch that is locked behind the beta flag. For instance, the new potions in the beta branch do not exist in the stable branch currently, so the BetaMode mod will not give you access to them.
