### ISSUE TITLE
ModTheSpire issues (The Construct)

### ISSUE THREAD

**Issue by jacobtenner** [kiooeht/ModTheSpire#41]
I've place ModTheSpire in my folder, and then the mod in the mods folder and when I try to run the .jar, this is what I get. What do I need to do to resolve this issue?

`Debug mode!
Java version: 1.8.0_144
Slay the Spire version: 05-17-2018
ModTheSpire version: 2.6.0
Mod list: constructmod (0.5.2), 
Finding core patches...
Finding patches...
Injecting patches...
Patch [com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit]
  Patching [com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()]
    Adding Insert @ 248...

{
com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit.Insert($0, $$);
}
Patch [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
  Patching [com.megacrit.cardcrawl.credits.CreditsScreen()]
    Adding Insert @ r5 (abs:57)...

{
float[] __tmpY = new float[]{tmpY};
com.evacipated.cardcrawl.modthespire.patches.CreditsModList.Insert($0, $$, __tmpY);
tmpY = __tmpY[0];
}
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.setMainMenuButtons()]
    Adding Insert @ r4 (abs:150)...

{
int[] __index = new int[]{index};
com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem.Insert($0, $$, __index);
index = __index[0];
}
Patch [constructmod.patches.BackToBasicsPatch]
  Patching [com.megacrit.cardcrawl.events.thecity.BackToBasics.buttonEffect(int)]
    Adding Insert @ r30 (abs:94)...

{
constructmod.patches.BackToBasicsPatch.Insert($0, $$);
}
Patch [constructmod.patches.PandorasBoxPatch]
  Patching [com.megacrit.cardcrawl.relics.PandorasBox.onEquip()]
    Adding Insert @ r12 (abs:47)...

{
constructmod.patches.PandorasBoxPatch.Insert($0, $$);
}
Patch [constructmod.patches.ReboundCardPatch]
  Patching [com.megacrit.cardcrawl.actions.utility.UseCardAction(com.megacrit.cardcrawl.cards.AbstractCard,com.megacrit.cardcrawl.core.AbstractCreature)]
    Adding Insert @ r6 (abs:28)...

{
constructmod.patches.ReboundCardPatch.Insert($0, $$);
}
Patch [constructmod.patches.KnowingSkullPatch]
  Patching [com.megacrit.cardcrawl.events.thecity.KnowingSkull()]
    Adding Insert @ r5 (abs:68)...

{
constructmod.patches.KnowingSkullPatch.Insert($0, $$);
}
Patch [constructmod.patches.VampiresPatch]
  Patching [com.megacrit.cardcrawl.events.thecity.Vampires.replaceAttacks()]
    Adding Insert @ r8 (abs:139)...

{
constructmod.patches.VampiresPatch.Insert($0, $$);
}
Patch [constructmod.patches.GremlinMatchPatch]
  Patching [com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.initializeCards()]
    Adding Insert @ r32 (abs:90)...

{
constructmod.patches.GremlinMatchPatch.Insert($0, $$, retVal);
}
Patch [constructmod.patches.CharScreenSelectFXPatch]
  Patching [com.megacrit.cardcrawl.screens.charSelect.CharacterOption.updateHitbox()]
    Adding Insert @ r52 (abs:185)...

{
constructmod.patches.CharScreenSelectFXPatch.Insert($0, $$);
}
Patch [constructmod.patches.CardLibraryPatch]
  Patching [com.megacrit.cardcrawl.helpers.CardLibrary.getCopy(java.lang.String,int,int)]
    Replacing...
Patch [com.evacipated.cardcrawl.modthespire.patches.MainMenuModList]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.MainMenuModList.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
  Patching [com.megacrit.cardcrawl.credits.CreditsScreen()]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.CreditsModList.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModMenuButton$SetLabel]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MenuButton.setLabel()]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModMenuButton$SetLabel.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.TopPanelModList]
  Patching [com.megacrit.cardcrawl.ui.panels.TopPanel.updateTips()]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.TopPanelModList.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModMenuButton$ButtonEffect]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MenuButton.buttonEffect()]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModMenuButton$ButtonEffect.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Update]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.update()]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Update.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(com.badlogic.gdx.graphics.g2d.SpriteBatch)]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render.Postfix($0, $$);
Done.
Compiling patched classes...
  com.badlogic.gdx.backends.lwjgl.LwjglApplication
  com.megacrit.cardcrawl.credits.CreditsScreen
  com.megacrit.cardcrawl.helpers.CardLibrary
  com.megacrit.cardcrawl.screens.charSelect.CharacterOption
  com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen
  com.megacrit.cardcrawl.screens.mainMenu.MenuButton
  com.megacrit.cardcrawl.ui.panels.TopPanel
  com.megacrit.cardcrawl.actions.utility.UseCardAction
  com.megacrit.cardcrawl.relics.PandorasBox
  com.megacrit.cardcrawl.events.shrines.GremlinMatchGame
  com.megacrit.cardcrawl.events.thecity.BackToBasics
  com.megacrit.cardcrawl.events.thecity.KnowingSkull
  com.megacrit.cardcrawl.events.thecity.Vampires
Done.
Patching enums...
com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen$CurScreen
  com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen$1
1 switch statement(s)
2018-05-25 00:30:08,453 Thread-4 ERROR Unable to move file C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire.log to C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire-2018-05-25-3.log: java.nio.file.FileSystemException C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire.log -> C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire-2018-05-25-3.log: The process cannot access the file because it is being used by another process.

2018-05-25 00:30:08,453 Thread-4 ERROR Unable to delete file C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire.log: java.nio.file.FileSystemException C:\Users\BBy983\Desktop\Applications\Slay.the.Spire.Patch.25\sendToDevs\logs\SlayTheSpire.log: The process cannot access the file because it is being used by another process.

com.megacrit.cardcrawl.screens.mainMenu.MenuButton$ClickResult
  com.megacrit.cardcrawl.screens.mainMenu.MenuButton$1
1 switch statement(s)

com.megacrit.cardcrawl.characters.AbstractPlayer$PlayerClass
  com.megacrit.cardcrawl.cards.AbstractCard$1
  com.megacrit.cardcrawl.characters.AbstractPlayer$1
  com.megacrit.cardcrawl.core.CardCrawlGame$1
  com.megacrit.cardcrawl.daily.DailyScreen$1
  com.megacrit.cardcrawl.dungeons.AbstractDungeon$1
  com.megacrit.cardcrawl.events.shrines.GremlinMatchGame$1
  com.megacrit.cardcrawl.events.thebeyond.SpireHeart$1
  com.megacrit.cardcrawl.events.thecity.KnowingSkull$1
  com.megacrit.cardcrawl.events.thecity.Vampires$1
  com.megacrit.cardcrawl.helpers.CardLibrary$1
  com.megacrit.cardcrawl.helpers.PotionHelper$1
  com.megacrit.cardcrawl.helpers.RelicLibrary$1
  com.megacrit.cardcrawl.relics.AncientTeaSet$1
  com.megacrit.cardcrawl.relics.ArtOfWar$1
  com.megacrit.cardcrawl.relics.CursedKey$1
  com.megacrit.cardcrawl.relics.Ectoplasm$1
  com.megacrit.cardcrawl.relics.GremlinHorn$1
  com.megacrit.cardcrawl.relics.HappyFlower$1
  com.megacrit.cardcrawl.relics.Lantern$1
  com.megacrit.cardcrawl.relics.PhilosopherStone$1
  com.megacrit.cardcrawl.relics.RunicDome$1
  com.megacrit.cardcrawl.relics.Sozu$1
  com.megacrit.cardcrawl.relics.Sundial$1
  com.megacrit.cardcrawl.relics.Test1$1
  com.megacrit.cardcrawl.relics.VelvetChoker$1
  com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue$1
  com.megacrit.cardcrawl.screens.CharSelectInfo$1
  com.megacrit.cardcrawl.screens.DeathScreen$1
  com.megacrit.cardcrawl.screens.charSelect.CharacterOption$1
  com.megacrit.cardcrawl.screens.leaderboards.FilterButton$1
  com.megacrit.cardcrawl.screens.options.OptionsPanel$1
  com.megacrit.cardcrawl.screens.options.SettingsScreen$1
  com.megacrit.cardcrawl.screens.runHistory.RunHistoryScreen$1
  com.megacrit.cardcrawl.screens.stats.CharStat$1
  com.megacrit.cardcrawl.screens.stats.StatsScreen$1
  com.megacrit.cardcrawl.steam.SteamSaveSync$1
  com.megacrit.cardcrawl.ui.panels.EnergyPanel$1
  com.megacrit.cardcrawl.unlock.UnlockTracker$1
  com.megacrit.cardcrawl.vfx.CardTrailEffect$1
39 switch statement(s)

com.megacrit.cardcrawl.cards.AbstractCard$CardColor
  com.megacrit.cardcrawl.cards.AbstractCard$1
  com.megacrit.cardcrawl.dungeons.AbstractDungeon$1
  com.megacrit.cardcrawl.helpers.CardLibrary$1
  com.megacrit.cardcrawl.screens.SingleCardViewPopup$1
  com.megacrit.cardcrawl.screens.runHistory.TinyCard$1
5 switch statement(s)

com.megacrit.cardcrawl.helpers.CardLibrary$LibraryType
  com.megacrit.cardcrawl.helpers.CardLibrary$1
1 switch statement(s)
Done.
Setting isModded = true...Done.
Adding ModTheSpire to version...Done.
Initializing mods...
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: basemod/interfaces/PostInitializeSubscriber
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:33)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:217)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: basemod.interfaces.PostInitializeSubscriber
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 17 more`

**Comment by kiooeht** [comment]
The Construct, like almost all of the mods that exist, has BaseMod as a dependency. You need to download the latest release of BaseMod (https://github.com/daviscook477/BaseMod/releases) and load it along with The Constuct.
