### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by hungwei97** [kiooeht/ModTheSpire#43]
For some reason, after downloading Mod week 27, I crashed whenever entering to rest sites.

**Comment by kiooeht** [comment]
If you're using the Black Mage Mod, part of the week 26 update to the game broke it and the mod hasn't been updated to fix that.

**Comment by hungwei97** [comment]
ah, i see.. thank you for the speedy reply.. working fine after turning off Black Mage Mod.. Thank you 👍
