### ISSUE TITLE
Unable to launch because of error 

### ISSUE THREAD

**Issue by Braydenpiag** [kiooeht/ModTheSpire#46]
![image](https://user-images.githubusercontent.com/35677732/41431804-1fc535c2-6fe2-11e8-94fd-ccdaa9fc41cc.png)
![image](https://user-images.githubusercontent.com/35677732/41431816-291d1248-6fe2-11e8-864b-e48c20dc09ec.png)
When i try to launch the game, i get this error, How can i fix it? Below is the files in the install directory, aswell as the mods folder. 
![image](https://user-images.githubusercontent.com/35677732/41431841-3a12e9d8-6fe2-11e8-84f8-791fd12aa0a2.png)
![image](https://user-images.githubusercontent.com/35677732/41431874-4ece3db4-6fe2-11e8-80ce-60a1113cc774.png)

**Comment by kiooeht** [comment]
You're using an extremely old version of BaseMod. You can download the latest version from https://github.com/daviscook477/BaseMod/releases

**Comment by Braydenpiag** [comment]
Also, how can i open the dev. Console?

**Comment by kiooeht** [comment]
Both ModTheSpire and BaseMod do not support the beta branch. They will sometimes work on the beta if its not too different, but it's up to luck whether they'll work with any given beta update.

You have to first enable the dev console and set a hotkey for it. Both can be done by opening Mods>BaseMod>Config from the main menu.
