### ISSUE TITLE
im having a error when trying to launch heres the log

### ISSUE THREAD

**Issue by healspell** [kiooeht/ModTheSpire#48]
Version Info:
 - Java version (1.8.0_171)
 - Slay the Spire (06-28-2018)
 - ModTheSpire (2.7.0)
Mod list:
 - basemod (2.14.0)
 - betterrewardsmod (4.0.0)
 - cagethespire (1.0.0)
 - customclimb (0.3.2)
 - MadScienceMod (0.1.7)
 - STS_AlwaysWhale (0.0.1)
 - witchmod (0.9.1)
 - superfastmode (0.8.1)

Begin patching...
Finding core patches...
Finding patches...
javassist.NotFoundException: com.megacrit.cardcrawl.screens.mainMenu.CardLibraryScreen
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
BaseMod (and therefore pretty much every mod) no longer works with the latest update of the game.
I'll be fixing it later today and will let you know when a fixed release is out.

**Comment by healspell** [comment]
Thank you your doing something great for the community

**Comment by BeeHutch** [comment]
Looks like someone has already maybe figured out a fix, CardLibraryScreen has moved from mainMenu to compendium, credit this knowledge to Kobting who has done a pull request on the base mod.
but in all honesty I don't have dev tools installed on my personal laptop to verify the work.
hopefully we are all back up and running soon.

**Comment by kiooeht** [comment]
New BaseMod is out for week 31.
https://github.com/daviscook477/BaseMod/releases/tag/v2.15.0
