### ISSUE TITLE
Mod the spire 2.7.0 can lauch but sees none of my mods

### ISSUE THREAD

**Issue by Sai001** [kiooeht/ModTheSpire#49]
I have done the tutorial on how to install mods : https://www.youtube.com/watch?v=r2m2aL1eEjw

Modthespire.jar is lauching when I double-click it (had to run jarfix). And I have put the mods i want into the mods folder.

But they don't show up when I launch mod the spire.

I have put base mod week 30 https://github.com/daviscook477/BaseMod/releases

Modthespire week 30 https://github.com/daviscook477/BaseMod/releases

and fruitymods (the seeker character).

I can't play him because fruitymods doesn't show up.

Any advice? (Screenshot included).
![1](https://user-images.githubusercontent.com/6641485/42109408-80c8f21c-7bab-11e8-93d9-c677d03f2a7f.png)

**Comment by Sai001** [comment]
maybe it's because it's friday?

**Comment by Sai001** [comment]
I've moved the modthespire jar file one folder up to the slaythespire folder and I get mods now but base mod week 30 is in yellow (see picture). Week 31 update is out from the devs so I'm assumiong I have to wait for the base mod update.
![2](https://user-images.githubusercontent.com/6641485/42112482-e930aeee-7bb5-11e8-9fc7-c79b03da0d38.png)

**Comment by kiooeht** [comment]
You're correct that the problem was the week 31 update of the game.
A new version of BaseMod is now out supporting week 31.
https://github.com/daviscook477/BaseMod/releases/tag/v2.15.0
