### ISSUE TITLE
8 more

### ISSUE THREAD

**Issue by Andrew2562** [kiooeht/ModTheSpire#51]
after I run Modthespire and choose mods including Basemod I see 8 more...
 and nothing happens

![screenshot_1 png png](https://user-images.githubusercontent.com/40774225/42183247-be4ab04e-7e49-11e8-9be1-2e5e8765eb5c.png)

**Comment by kiooeht** [comment]
You need to reorder your mods so that BaseMod is first. You can reorder them using drag and drop.
Also, the Necromancer mod hasn't been updated in a long time, there's a good chance it won't work, so don't be surprised if it doesn't.

**Comment by Andrew2562** [comment]
thank you a lot
