### ISSUE TITLE
An issue with the Grinning Jar

### ISSUE THREAD

**Issue by Poshriel** [kiooeht/ModTheSpire#53]
The grinning jar, I don't even know which mod got me it, but there's a bit of a bug.  I'm at a point where I'm on my 11th card, the one right before you get another one of the skills it provides.  I was at a shop, bought a card, and the game shut down.

I thought I'd try to see if it was that card, apparently it wasn't.  Because when I got a curse from my curse key, it also shut down.  So I think there's a problem with gaining that card from the jar in general.  I was able to get the two cards when I picked up the jar.  But not after.

**Comment by kiooeht** [comment]
Grinning Jar is from Replay the Spire, please report the issue there: https://github.com/AstroPenguin642/Replay-the-Spire
