### ISSUE TITLE
unable to find desktop1.jar

### ISSUE THREAD

**Issue by foiegras23** [kiooeht/ModTheSpire#59]
I get an error thrown when I try to load.  I have read as much as I can find ... any clues to what I'm missing?

**Comment by foiegras23** [comment]
just so I'm clear the title 

unable to find desktop1.jar

is the error I'm catching.

**Comment by kiooeht** [comment]
I'm presuming this (https://www.reddit.com/r/slaythespire/comments/8ym216/assistance_in_modding_instal_error/e2bxf5q/) is also you.

`desktop-1.0.jar` is from the base game and contains everything the game requires to run.

Compared to your setup, this is how my game comes installed (plus mods).

![explorer_2018-07-13_16-47-17](https://user-images.githubusercontent.com/236842/42718285-75f8a0be-86bc-11e8-9a62-7699690d456f.png)

What's in the `spire` directory you have? I don't have that directory.

**Comment by foiegras23** [comment]
You are correct.  I reinstalled as directed and I got desktop...

I am not sure how I screwed that up or what went wrong I was playing all day with no issues?? 

You're a hero though.  Thank you.  Seems to be working now.
