### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by gabriel-dehan** [kiooeht/ModTheSpire#61]
Hello, I can't seem to install on mac, I am pretty sure I have followed the instructions properly though:

```
$ cd ~/Applications/Slay the Spire.app/Contents/Resources
$ java -jar ModTheSpire.jar
```
Gives me back:
```
ERROR: Failed to find Steam installation.
Exception in thread "main" java.lang.NullPointerException
	at com.evacipated.cardcrawl.modthespire.SteamSearch.containsAcfFile(SteamSearch.java:94)
	at com.evacipated.cardcrawl.modthespire.SteamSearch.prepare(SteamSearch.java:39)
	at com.evacipated.cardcrawl.modthespire.SteamSearch.findDesktopJar(SteamSearch.java:19)
	at com.evacipated.cardcrawl.modthespire.Loader.main(Loader.java:91)
```

I have java 8 installed and my structure is like that:

```
.
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── run.sh
    └── Resources
        ├── MTS.sh
        ├── ModTheSpire.jar
        ├── mods
        └── shortcut.icns
```

Thanks :)

**Comment by kiooeht** [comment]
I don't have a mac, so it's hard to test anything myself.

`Slay the Spire.app/Contents/Resources/` should contain a file `desktop-1.0.jar` that ModTheSpire looks for. Apparently it might be hidden. Hopefully https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/ has proper instructions for you to see hidden files.

Just being able to see hidden files probably won't fix the issue, but I'd like to see the layout of the hidden files.

**Comment by gabriel-dehan** [comment]
There is no desktop-1.0.jar inside no, it doesn't seem to be hidden either, I just checked. 

If you need anymore info or for me to do some thing for you to debug please ask, I am a developer (just not java) I may be able to help. Cheers

**Comment by kiooeht** [comment]
Are you sure it's not there? The one person I know who found it said it was hidden and they had to use a terminal command and relaunch Finder, but after that they could see it.

**Comment by gabriel-dehan** [comment]
Okay I found the answer! 

It was actually not in ~/Applications/Slay The Spire.app/Contents/Ressources` but instead inside `~/Library/Application\ Support/Steam/steamapps/common/SlayTheSpire/SlayTheSpire.app/Contents/Resources`.

Might depend on the installation or a few things but it might be nice to add that to the readme :)

**Comment by kiooeht** [comment]
Alright, thanks for the info.
