### ISSUE TITLE
Modloader Not Detecting Updates

### ISSUE THREAD

**Issue by vizthex123** [kiooeht/ModTheSpire#74]
Whenever I load up ModtheSpire, the update checker just infinitely spins when it should be a green check saying everything is up to date or telling me I need updates or whatever.

I have the latest version of Mod the Spire and BaseMod, and am not on the Beta branch.

**Comment by kiooeht** [comment]
This is an issue caused by the Ascension Plus mod using an incorrect url for its update checking (https://github.com/will2216/Ascension-plus/issues/2). I've informed them along with adding some checks to the code so this shouldn't happen in the future.
