### ISSUE TITLE
Help with ModTheSpire not working.

### ISSUE THREAD

**Issue by NoblezDomain** [kiooeht/ModTheSpire#88]
Hi! I just downloaded the newest version, I've never modded StS before and I don't know anything on java, what exactly is happening here?

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (08-30-2018)
 - ModTheSpire (3.1.0)
Mod list:
 - basemod (2.18.0)
 - ReplayTheSpireMod (1.1.1)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CardIDModID:
No method [ctor(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, java.lang.String, com.megacrit.cardcrawl.cards.AbstractCard$CardType, com.megacrit.cardcrawl.cards.AbstractCard$CardColor, com.megacrit.cardcrawl.cards.AbstractCard$CardRarity, com.megacrit.cardcrawl.cards.AbstractCard$CardTarget, com.megacrit.cardcrawl.cards.DamageInfo$DamageType)] found on
class [com.megacrit.cardcrawl.cards.AbstractCard]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:268)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:176)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:192)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
You have an old release of BaseMod. Grab the latest from https://github.com/daviscook477/BaseMod/releases/latest.
