### ISSUE TITLE
ModTheSpire.jar wont open

### ISSUE THREAD

**Issue by purplecompany** [kiooeht/ModTheSpire#90]
First time user here, after reading the troubleshooting page I still can't get it running. 
My ModTheSpire.jar file isn't labeled an executable jar file like the ones I saw on different youtube videos. I am using java 8 update 181, when I click ModTheSpire.jar nothing happens & when I run it using command prompt I get a different message. attached are screenshots of my slaythespire folder and command prompt message. please help! ty!

![slaythespirefolder](https://user-images.githubusercontent.com/43502359/45920494-ecdfdf80-be61-11e8-8770-7ea9ab79a626.JPG)
![commandline](https://user-images.githubusercontent.com/43502359/45920495-ecdfdf80-be61-11e8-808d-53153fafd144.JPG)

**Comment by kiooeht** [comment]
As the troubleshooting guide says, run the provided script `MTS.cmd` to start ModTheSpire. Just double-click it.
