### ISSUE TITLE
Do not compute

### ISSUE THREAD

**Issue by Chickdeez** [kiooeht/ModTheSpire#94]
Hi,

I loaded all mods and required .jars yesterday and all worked just fine but today nothing works. 

My programming skills are -20 so please simple "yes or no" questions :)

Thank you in advance!

I reloaded all of them again just to be sure but all I get is this:

ModVersion Info:
 - Java version (1.8.0_181)
 - Slay the Spire (10-11-2018)
 - ModTheSpire (3.2.0)
Mod list:
 - basemod (3.5.0)
 - beakedthecultist-sts (0.4.4)
 - constructmod (0.9.7)
 - fruitymod-sts (1.0.0)
 - MadScienceMod (0.2.2)
 - chronomuncher (0.10.0)
 - The Valiant
 - witchmod (1.1.1)
 - Team TouhouSpire 04 - Yuyuko (0.2.3)

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.MissingParamTypesException: Patch basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.BlueCardsPatch
Patching com.megacrit.cardcrawl.helpers.CardLibrary.addBlueCards:
Has overloads and no paramtypes defined
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
Yesterday's update to the game brought a lot of backend changes to the game that break BaseMod in a lot of ways. I've been working on fixing it, but there are a lot of changes to work through, it will take some time.

**Comment by Chickdeez** [comment]
Ah thank you for the fast reply. I didn't even notice there was an update yesterday. Once again, thanks!
