### ISSUE TITLE
Mod auto-update freezing

### ISSUE THREAD

**Issue by Energaic** [kiooeht/ModTheSpire#98]
This issue is fairly simple, when I try to use the auto-update function of MtS, all the auto-update icons on the mods freeze, and the auto-update never completes. While it is true that they could be updated manually, I would have no idea which ones have been updated or not without looking through the entire modlist. After using the .cmd file _run I was able to find that it was initially caused by a new mod (or so it seemed, since it was returning with an error from that mod) so I deleted that mod (The Warrior). After that, the issue was still occurring, so checking the _run.cmd file again, I found that every update-needing mod had that same issue: "Server returned HTTP response code 403 for URL: [Insert mod URL here]". That is all I have for this, unfortunately. Sorry if this is not enough for this type of issue!

**Comment by kiooeht** [comment]
I don't know what was causing the first problem, but I suspect the second problem was you running into Github's rate limiting. You're only allowed to make 60 requests an hour (each mod is a separate request), so checking for mod updates while having a lot of mods will make you hit that limit pretty quickly.

If that is the problem, just wait an hour before checking for updates again and you should be alright.

**Comment by Energaic** [comment]
Yeah, the rate limiting appeared to be the issue; it's working fine now. I don't know what was going on with the warrior mod, but that too is now working fine (It did have a hotfix, so it was probably that.) Thank you!
